---
name: LifeSOS to MQTT
version: 2.1
slug: lifesos2mqtt
description: MQTT client that interfaces with LifeSOS alarm systems.
arch:
  - aarch64
  - amd64
startup: application
init: false
map:
  - config:rw
services:
  - mqtt:need

